name: Pride
version: 1.0.0
main: me.toshiro.pride.Pride
description: Archbishop's Companion system
author: _ToshiroCyMc

commands:
  pride:
    description: Archbishop's Companion management
    usage: /pride <bless|unbless|reload> [player]
    permission: pride.admin
    permission-message: Only the Archbishop can use this command!

permissions:
  pride.admin:
    description: Allows use of Pride admin commands
    default: false
